
<?php
Zend_Layout::getMvcInstance()->disableLayout();
$enabled= $this->enabledSitemapPages;
$allSitemapPages = $this->allSitemapPages;
?>


        <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-sitemap fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><?php echo $this->escape($enabled . ' / ' . $allSitemapPages );?></div>
                                    <div>Enabled/All</div>
                                </div>
                            </div>
                        </div>
                        <a href="<?php echo $this->url(array('controller'=>'admin_sitemap'), "default", true); ?>">
                            <div class="panel-footer">
                                <span class="pull-left">View Details about Sitemap Pages <i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
</div>