<?php
$this->headTitle('Members - Edit Member');
?>
<div class="page-header">
    <h1>Members</h1>
    <small>Edit Member</small>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right">
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href='<?php echo $this->url(array('controller'=>'admin_members', 'action'=>'index'), 'default', true) ?>' 
                    <button type="button" class="btn btn-default">
                        <i class="glyphicon glyphicon-arrow-left"></i>Back to all members</button></a>
                </div>
                
            </div>
            <div class="panel-body">
                <form class="form-horizontal">
                    <fieldset>

                        <!-- Form Name -->
                        <legend>Edit Member</legend>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="first_name">First Name</label>  
                            <div class="col-md-4">
                                <input name="first_name" class="form-control input-md" id="first_name" required="" type="text" placeholder="enter member's first name">
                                <span class="help-block">min 3 max 255 characters</span>  
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="last_name">Last Name</label>  
                            <div class="col-md-4">
                                <input name="last_name" class="form-control input-md" id="last_name" required="" type="text" placeholder="enter member's last name">
                                <span class="help-block">min 3 max 255 characters</span>  
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="email">Email</label>  
                            <div class="col-md-4">
                                <input name="email" class="form-control input-md" id="email" required="" type="text" placeholder="enter member's email">
                                <span class="help-block">user@domain</span>  
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="work_title">Work Title</label>  
                            <div class="col-md-4">
                                <input name="work_title" class="form-control input-md" id="work_title" type="text" placeholder="enter member's work title">
                                <span class="help-block">min 3 max 255 characters</span>  
                            </div>
                        </div>

                        <!-- Textarea -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="resume">Resume</label>
                            <div class="col-md-4">                     
                                <textarea name="resume" class="form-control" id="resume"></textarea>
                            </div>
                        </div>

                        <!-- Button (Double) -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="Cancel"></label>
                            <div class="col-md-8">
                                <button name="Cancel" class="btn btn-default" id="Cancel">Cancel</button>
                                <button name="Save" class="btn btn-success" id="Save">Save</button>
                            </div>
                        </div>

                    </fieldset>
                </form>

            </div>
        </div>
    </div>
</div>