<?php

$this->headTitle('Users');

?>
<div class="page-header">
  <h1>Users</h1>
</div>
<div class="row">
	<div class="col-lg-12" id="system-messages-container">
		<?php echo $this->systemMessagesHtml($this->systemMessages);?>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading text-right">
				<div class="btn-group" role="group" aria-label="...">
					<a 
						href="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'add'), 'default', true);?>"
						class="btn btn-default"
						><i class="glyphicon glyphicon-plus"></i> Add user</a>
				</div>
			</div>
			<div class="panel-body">
				
				<table id="rows-table" class="table table-striped table-hover">
					<thead>
						<tr>
							<th class="text-center">Status</th>
							<th>Username</th>
							<th>First Name</th>
							<th>Last Name</th>
							<th>Email</th>
							<th class="text-center">#</th>
						</tr>
					</thead>
					<tbody>
						<?php /*
						foreach ($this->users as $user) {
							if ($user['status'] == Application_Model_DbTable_CmsUsers::STATUS_DISABLED) {
							?>
						<tr data-user-id="<?php echo $this->escape($user['id']);?>" class="danger">
							<td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
							<td><?php echo $this->escape($user['username']);?></td>
							<td><?php echo $this->escape($user['first_name']);?></td>
							<td><?php echo $this->escape($user['last_name']);?></td>
							<td><?php echo $this->escape($user['email']);?></td>
							<td class="text-center">
								<div class="btn-group btn-group-sm" role="group" aria-label="...">
									<a 
										href="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'edit', 'id' => $user['id']), 'default', true);?>"
										type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
									<button data-user-name="<?php echo $this->escape($user['first_name']) . " " . $this->escape($user['last_name']);?>" data-user-id="<?php echo $this->escape($user['id']);?>" data-action="enable" type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
                                                                        <button data-user-name="<?php echo $this->escape($user['first_name']) . " " . $this->escape($user['last_name']);?>" data-user-id="<?php echo $this->escape($user['id']);?>" data-action="reset-password" type="button" class="btn btn-default" title="reset"><i class="fa fa-unlock-alt"></i></button>
									<button data-user-name="<?php echo $this->escape($user['first_name']) . " " . $this->escape($user['last_name']);?>" data-user-id="<?php echo $this->escape($user['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
								
								</div>
							</td>
						</tr>
							<?php
							} else {
							?>
						<tr data-user-id="<?php echo $this->escape($user['id']);?>">
							<td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
							<td><?php echo $this->escape($user['username']);?></td>
							<td><?php echo $this->escape($user['first_name']);?></td>
							<td><?php echo $this->escape($user['last_name']);?></td>
							<td><?php echo $this->escape($user['email']);?></td>
							<td class="text-center">
								<div class="btn-group btn-group-sm" role="group" aria-label="...">
									<a 
										href="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'edit', 'id' => $user['id']), 'default', true);?>"
										type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
									<button data-user-name="<?php echo $this->escape($user['first_name']) . " " . $this->escape($user['last_name']);?>" data-user-id="<?php echo $this->escape($user['id']);?>" data-action="disable" type="button" class="btn btn-default" title="disable"><i class="glyphicon glyphicon-remove"></i></button>
                                                                        <button data-user-name="<?php echo $this->escape($user['first_name']) . " " . $this->escape($user['last_name']);?>" data-user-id="<?php echo $this->escape($user['id']);?>" data-action="reset-password" type="button" class="btn btn-default" title="reset"><i class="fa fa-unlock-alt"></i></button>
									<button data-user-name="<?php echo $this->escape($user['first_name']) . " " . $this->escape($user['last_name']);?>" data-user-id="<?php echo $this->escape($user['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
								
								</div>
							</td>
						</tr>
							<?php
							}
							?>
						
							<?php
						}
						*/?>
						
					</tbody>
				</table>
				
				
				
			</div>
		</div>
	</div>
</div>
<form method="post" action="<?php echo $this->url(array('controller'=>'admin_users', 'action'=>'delete'), 'default', true); ?>" id="delete-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="delete">
    <input type="hidden" name="id" value="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete user</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete user <span id="delete-user"></span>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i>Delete</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->
<form method="post" action="<?php echo $this->url(array('controller'=>'admin_users', 'action'=>'disable'), 'default', true); ?>" id="disable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="disable">
    <input type="hidden" name="id" value="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Disable user</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to disable user <span id="disable-user"></span>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i>Disable</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->


<form method="post" action="<?php echo $this->url(array('controller'=>'admin_users', 'action'=>'enable'), 'default', true); ?>" id="enable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="enable">
    <input type="hidden" name="id" value="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Enable user</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to enable user <span id="enable-user"></span>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"></i>Enable</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form id="reset-password-warning-dialog" class="modal fade" tabindex="-1" role="dialog" method="post" action="<?php echo $this->url( array('controller' => 'admin_users', 'action' => 'resetPassword'), 'default', true) ;?>">
    <input type="hidden" name="task" value="reset">
    <input type="hidden" name="id" value="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Reset user password</h4>
      </div>
      <div class="modal-body">
          <p>Are you sure you want to reset password of the user <span id="reset-password-user"></span>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger">Reset</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->
<div id="message-templates" style="display: none">
    <div data-container="message-box-success" class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span data-container="message-text"></span>
    </div>
    
    <div data-container="message-box-error" class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span data-container="message-text"></span>
    </div>
    
    
</div>
<!--//
//$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.css'));
//$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.js'));
//-->

 <?php
 $this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css'));
 //$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/datatables-responsive/css/dataTables.responsive.css'));
 $this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/datatables/media/js/jquery.dataTables.min.js'));
 $this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js'));
 $this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/datatables-responsive/js/dataTables.responsive.js'));
 ?>
<script>
<?php $this->inlineScript()->captureStart(); ?>

 $('#rows-table').on('click', '[data-action="delete"]', function(e) {
    
    e.preventDefault();
    e.stopPropagation();
    
    //calculate target element
    var target = $(this).is('[data-action="delete"]') ? $(this) : $(this).closest('[data-action="delete"]');
    
    var userId = target.attr('data-user-id');
    var userName = target.attr('data-user-name');
    //.val je funkcija za dodeljivanje vrednosti elemenata forme u ovom slucaju za polje sa nazivom "id"
    $('#delete-warning-dialog').find('[name="id"]').val(userId);
    $('#delete-user').text(userName);
    $('#delete-warning-dialog').modal('show');
 });   
 $('#rows-table').on('click', '[data-action="disable"]', function(e) {
    
    e.preventDefault();
    e.stopPropagation();
    
    //calculate target element
    var target = $(this).is('[data-action="disable"]') ? $(this) : $(this).closest('[data-action="disable"]');
    var userName = target.attr('data-user-name'); 
    var userId = target.attr('data-user-id');

    //.val je funkcija za dodeljivanje vrednosti elemenata forme u ovom slucaju za polje sa nazivom "id"
    $('#disable-warning-dialog').find('[name="id"]').val(userId);
    $('#disable-user').text(userName);
    $('#disable-warning-dialog').modal('show');
 });
 $('#rows-table').on('click', '[data-action="enable"]', function(e) {
    
    e.preventDefault();
    e.stopPropagation();
    
    //calculate target element
    var target = $(this).is('[data-action="enable"]') ? $(this) : $(this).closest('[data-action="enable"]');
    var userName = target.attr('data-user-name');
    var userId = target.attr('data-user-id');

    //.val je funkcija za dodeljivanje vrednosti elemenata forme u ovom slucaju za polje sa nazivom "id"
    $('#enable-warning-dialog').find('[name="id"]').val(userId);
    $('#enable-user').text(userName);
    $('#enable-warning-dialog').modal('show');
 });
 
  $('#rows-table').on('click', '[data-action="reset-password"]', function(e) {
        e.preventDefault();
        e.stopPropagation();
        
        var target = $(this).is('[data-action="reset-password"]') ? $(this) : $(this).closest('[data-action="reset-password"]');
        
        var userId = target.attr('data-user-id');
        var userName = target.attr('data-user-name');
        $('#reset-password-warning-dialog [name = "id"] ').val(userId);
        $('#reset-password-user').text(userName);
        $('#reset-password-warning-dialog').modal('show');
        
    });
   
  $('#rows-table').DataTable({
        columnDefs:[
            {targets: [5], orderable: false, searchable: false},// iskljucivanje pretrazivanja sadrzaja 5 kolone
            {targets: [0,5], className:'text-center'}//centriranje sadrzaja u kolonama 0 i 5
        ],
        order:[
            [2, 'asc']
        ],
        lengthMenu: [3, 10, 20, 50, 100 ],
        serverSide: true,//na svaki klik vrati informaciju
        processing:true,
        ajax: "<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'datatable'), 'default', true); ?>"//gde pitamo server
    });
    
  $('#disable-warning-dialog').on('submit', function(e) {
        
        e.preventDefault();//stop manual form submit
        
        var target = $(this).is('#disable-warning-dialog') ? $(this) : $(this).closest('#disable-warning-dialog');
        
        $.ajax({
          
          url: '<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'disable'), 'default', true) ?>',
          method: 'post',
          data: {
             
             task: 'disable',
             id: target.find('[name="id"]').val()//selektovanje preko atributa ide sa ovim []
             
            }
          
          
        }).done(function(data){
            
            if(data['status'] === 'ok'){
                
                //var messageBox = $('[data-container="message-box-success"]').last().clone(true);//true znaci kloniraj i handler u message boxu
                var messageBox = $('#message-templates').find('[data-container="message-box-success"]').clone(true);
                messageBox.find('[data-container="message-text"]').text(data['statusMessage']);
                
                $('#system-messages-container').append(messageBox);
                  //alert('Succes: ' + data['statusMessage']);
                  messageBox.delay(5000).fadeOut();
                }else{
                    //var messageBox = $('[data-container="message-box-error"]').last().clone(true);//true znaci kloniraj i handler u message boxu
                    var messageBox = $('#message-templates [data-container="message-box-error"]').clone(true);
                    
                    messageBox.find('[data-container="message-text"]').text(data['statusMessage']);
                    //$('#system-messages-container').empty(); zatvora prethodnu poruku za usera
                    $('#system-messages-container').append(messageBox);
                    //alert('Error: ' + data['statusMessage']);
                    messageBox.delay(5000).fadeOut();
                }
        
        
        }).fail(function(){//fail sluzi da pokaze da je doslo do greske u komunikaciji sa serverom
            //error in communication with server
            alert('Error:Server returned error')
        
        
        }).always(function(){
            target.modal('hide');
            //refresh table keep selected page
            $('#rows-table').DataTable().draw(false);//draw iscrtava tabelu nad kojim su prosledjeni parametri false vraca na stranu na kojoj smo trenutno
            });
    });
   
     $('#enable-warning-dialog').on('submit', function(e) {
        
        e.preventDefault();//stop manual form submit
        //ternarni za pozicioniranje na id 
        var target = $(this).is('#enable-warning-dialog') ? $(this) : $(this).closest('#enable-warning-dialog');
        //pocetak ajaxa
        $.ajax({
          //gde saljemo zahtev (na koju akciju) i kog je tipa zahtev
          url: '<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'enable'), 'default', true) ?>',
          method: 'post',
          data: {
             //saljemo task iz hidden forme
             task: 'enable',
             id: target.find('[name="id"]').val()//selektovanje preko atributa ide sa ovim []
             
            }
          
          
        }).done(function(data){
            //proveravamo sadrzaj ukolioko jeste baci poruku success ukoliko nije baci error
            if(data['status'] === 'ok'){
                
                //var messageBox = $('[data-container="message-box-success"]').last().clone(true);//kloniraj i handler u message boxu
                var messageBox = $('#message-templates').find('[data-container="message-box-success"]').clone(true);
                
                messageBox.find('[data-container="message-text"]').text(data['statusMessage']);
                
                $('#system-messages-container').append(messageBox);
                
                messageBox.delay(5000).fadeOut();
                  
                }else{
                    //var messageBox = $('[data-container="message-box-error"]').last().clone(true);
                    var messageBox = $('#message-templates').find('[data-container="message-box-success"]').clone(true);
                    
                    messageBox.find('[data-container="message-text"]').text(data['statusMessage']);
                
                    $('#system-messages-container').append(messageBox);
                    
                    messageBox.delay(5000).fadeOut();
                    
                }
        
        
        }).fail(function(){
            //error in communication with server
            alert('Error:Server returned error')
        
        
        }).always(function(){
            target.modal('hide');
            //draw iscrtava tabelu nad kojim su prosledjeni parametri false vraca na stranu na kojoj smo trenutno
            $('#rows-table').DataTable().draw(false);
            });
    });
    
 $('#reset-password-warning-dialog').on('submit', function(e) {
        
        e.preventDefault();
        
        var target = $(this).is('#reset-password-warning-dialog') ? $(this) : $(this).closest('#reset-password-warning-dialog');
        
        $.ajax({
          
          url: '<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'resetpassword'), 'default', true) ?>',
          method: 'post',
          data: {
             
             task: 'reset',
             id: target.find('[name="id"]').val()
             
            }
          
        }).done(function(data){
            
            if(data['status'] === 'ok'){
                
                //var messageBox = $('[data-container="message-box-success"]').last().clone(true);
                
                var messageBox = $('#message-templates').find('[data-container="message-box-success"]').clone(true);
                
                messageBox.find('[data-container="message-text"]').text(data['statusMessage']);
                
                $('#system-messages-container').append(messageBox);
                
                messageBox.delay(5000).fadeOut();
                
                }else{
                    //var messageBox = $('[data-container="message-box-error"]').last().clone(true);
                    var messageBox = $('#message-templates').find('[data-container="message-box-success"]').clone(true);
                    
                    messageBox.find('[data-container="message-text"]').text(data['statusMessage']);
                
                    $('#system-messages-container').append(messageBox);
                    
                    messageBox.delay(5000).fadeOut();
                }

        }).fail(function(){
            
            alert('Error:Server returned error')
        
        }).always(function(){
            target.modal('hide');
            
            $('#rows-table').DataTable().draw(false);
            });
    });

 $('#delete-warning-dialog').on('submit', function(e) {
        
        e.preventDefault();
        
        var target = $(this).is('#delete-warning-dialog') ? $(this) : $(this).closest('#delete-warning-dialog');
        
        $.ajax({
          
          url: '<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'delete'), 'default', true) ?>',
          method: 'post',
          data: {
             
             task: 'delete',
             id: target.find('[name="id"]').val()
             
            }
          
        }).done(function(data){
            
            if(data['status'] === 'ok'){
                
                //var messageBox = $('[data-container="message-box-success"]').last().clone(true);
                var messageBox = $('#message-templates').find('[data-container="message-box-success"]').clone(true);
                
                messageBox.find('[data-container="message-text"]').text(data['statusMessage']);
                
                $('#system-messages-container').append(messageBox);
                
                messageBox.delay(5000).fadeOut();
                  
                }else{
                   // var messageBox = $('[data-container="message-box-error"]').last().clone(true);
                   
                   var messageBox = $('#message-templates').find('[data-container="message-box-success"]').clone(true);
                    
                    messageBox.find('[data-container="message-text"]').text(data['statusMessage']);
                
                    $('#system-messages-container').append(messageBox);
                    
                    messageBox.delay(5000).fadeOut();
                    
                }

        }).fail(function(){
            
            alert('Error:Server returned error')
        
        }).always(function(){
            target.modal('hide');
            
            $('#rows-table').DataTable().draw(false);
            });
    });
    
<?php $this->inlineScript()->captureEnd(); ?> 
</script>