<?php
$this->headTitle('Profile - Change Password');
?>
<div class="page-header">
    <h1>Profile</h1>
    <small>Change Password</small>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right">
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href='<?php echo $this->url(array('controller' => 'admin_profile', 'action' => 'edit'), 'default', true) ?>' 
                        class="btn btn-default">
                        <i class="fa fa-user"></i>Edit Profile</a>

                </div>
            </div>
            <div class="panel-body">
                <form class="form-horizontal">
                    <fieldset>

                        <!-- Form Name -->
                        <legend>Change Password</legend>

                        <!-- Password input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="new_password">New Password</label>
                            <div class="col-md-4">
                                <input name="new_password" class="form-control input-md" id="new_password" required="" type="password" placeholder="enter new password">
                                <span class="help-block">min 5 max 255 characters</span>
                            </div>
                        </div>

                        <!-- Password input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="new_password_confirm">Confirm new password</label>
                            <div class="col-md-4">
                                <input name="new_password_confirm" class="form-control input-md" id="new_password_confirm" required="" type="password" placeholder="confirm new password">
                                <span class="help-block"></span>
                            </div>
                        </div>

                        <!-- Button (Double) -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="Cancel"></label>
                            <div class="col-md-8">
                                <button name="Cancel" class="btn btn-default" id="Cancel">Cancel</button>
                                <button name="Change Password" class="btn btn-success" id="Change Password">Change Password</button>
                            </div>
                        </div>

                    </fieldset>
                </form>

            </div>
        </div>
    </div>
</div>
