<?php
    $this->headTitle('Profile - Edit Profile');
?>
<div class="page-header">
    <h1>Profile</h1>
    <small>Edit Profile</small>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right">
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href='<?php echo $this->url(array('controller'=>'admin_profile', 'action'=>'changepassword'), 'default', true) ?>' 
                        class="btn btn-default">
                        <i class="fa fa-key"></i>Change Password</a>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal">
                        <fieldset>

                            <!-- Form Name -->
                            <legend>Edit Profile</legend>

                            <!-- Text input-->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="first_name">First Name</label>  
                                <div class="col-md-4">
                                    <input name="first_name" class="form-control input-md" id="first_name" type="text" placeholder="enter member">
                                    <span class="help-block">min 3 max 255 characters</span>  
                                </div>
                            </div>

                            <!-- Text input-->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="last_name">Last Name</label>  
                                <div class="col-md-4">
                                    <input name="last_name" class="form-control input-md" id="last_name" type="text" placeholder="enter member's first name">
                                    <span class="help-block">min 3 max 255 characters</span>  
                                </div>
                            </div>

                            <!-- Text input-->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="email">Email</label>  
                                <div class="col-md-4">
                                    <input name="email" class="form-control input-md" id="email" type="text" placeholder="enter member's email">
                                    <span class="help-block">user@domain</span>  
                                </div>
                            </div>

                            <!-- Button (Double) -->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="Cancel"></label>
                                <div class="col-md-8">
                                    <button name="Cancel" class="btn btn-default" id="Cancel">Cancel</button>
                                    <button name="Save" class="btn btn-success" id="Save">Save</button>
                                </div>
                            </div>

                        </fieldset>
                    </form>

                </div>
        </div>
    </div>
</div>
    </div>
