<?php
$askMember = $this->askMember;

echo $this->headTitle('Member - ' . $askMember['first_name'] . ' ' . $askMember['last_name']);
 ?>		
                <div id="highlighted">
			<div class="container">
                            <?php echo $this->headTitle('Contact');?>
				<div class="header">
					<h2 class="page-title">
						<span>Contact</span> 
						<small><?php echo $this->escape('Member - ' . $askMember['first_name'] . ' ' . $askMember['last_name']); ?></small>
					</h2>
				</div>
			</div>
		</div>
		<div id="content">
                    <div class="container">
                        <div class="row team-askMember">
                            <div class="col-sm-3">
                                <img alt="<?php echo $this->escape($askMember['first_name']); ?>" class="img-polaroid" src="<?php echo $this->memberImgUrl($askMember); ?>">
                            </div>
                            <div class="col-sm-9">
                                <h3>
                                    <?php echo $this->escape($askMember['first_name'] . ' ' . $askMember['last_name']); ?>
                                </h3>
                                <h5>
                                    <?php echo $this->escape($askMember['work_title']); ?>
                                </h5>
                                <p><?php echo $this->escape($askMember['resume']); ?></p>
                                <div class="social-media bordered-top-medium">
                                    <a data-original-title="Twitter" data-placement="top" class="_tooltip" href="#"><i class="fa fa-twitter"></i></a>
                                    <a data-original-title="Facebook" data-placement="top" class="_tooltip" href="#"><i class="fa fa-facebook"></i></a>
                                    <a data-original-title="LinkedIn" data-placement="top" class="_tooltip" href="#"><i class="fa fa-linkedin"></i></a>
                                    <a data-original-title="Google +" data-placement="top" class="_tooltip" href="#"><i class="fa fa-google-plus"></i></a>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="block">
                            <div class="row">
                                <div class="col-sm-6">
                                    <form action="#" id="contact-form">
                                        <div class="form-group">
                                            <input type="text" placeholder="Name" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <input type="email" placeholder="Email" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <textarea placeholder="Message" class="form-control" rows="15"></textarea>
                                        </div>
                                        <input type="button" value="Send Message" class="btn btn-primary">
                                    </form>
                                </div>
                                <div class="col-sm-6">
                                    <h3 class="block-title sub-title">
                                        <span>Other Ways To Get In Touch</span>
                                    </h3>
                                    <p><abbr title="Phone">P</abbr>: 011/3210-112</p>
                                    <p><abbr title="Fax">F</abbr>: 011/3210-112</p>
                                    <p><abbr title="Email">E</abbr>: office@cubes.rs</p>
                                    <p><abbr title="Address">A</abbr>: Bulevar Milutina Milankovića 181, 11000 Beograd</p>
                                    <a href="https://maps.google.co.uk/maps?q=London&amp;ie=UTF8&amp;hq=&amp;hnear=London,+United+Kingdom&amp;gl=uk&amp;t=m&amp;ll=51.510238,-0.127029&amp;spn=0.042735,0.102654&amp;z=12&amp;">
                                        <img class="img-polaroid" alt="Location map" src="/img/misc/map.png">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
		</div>